services:
  postgres:
    image: postgres:16-alpine
    container_name: taskdb
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-network

  redis:
    image: redis:7-alpine
    container_name: taskredis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: taskmq
    environment:
      RABBITMQ_DEFAULT_USER: taskuser
      RABBITMQ_DEFAULT_PASS: taskpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - task-network

  db-seed:
      image: node:20
      container_name: tasknode
      working_dir: /app
      volumes:
        - .:/app
        - node_modules:/app/node_modules
        - pnpm_store:/app/.pnpm-store
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        # Todas as formas possíveis de configuração
        DATABASE_URL: postgresql://taskuser:taskpass@postgres:5432/taskdb
        POSTGRES_HOST: postgres
        POSTGRES_PORT: "5432"
        POSTGRES_USER: taskuser
        POSTGRES_PASSWORD: taskpass
        POSTGRES_DB: taskdb
        NODE_ENV: development
        # Forçar IPv4
        NODE_OPTIONS: "--dns-result-order=ipv4first"
      command: ["./scripts/wait-and-seed.sh"]
      networks:
        - task-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  node_modules:      # Volume para node_modules
  pnpm_store:        # Volume para pnpm store

networks:
  task-network:
    driver: bridge